### ISSUE TITLE
Unable to execute the utility

### ISSUE THREAD

**Issue by akshits96** [snyk-tech-services/jira-tickets-for-new-vulns#108]
Hi the latest version is not executing for me.
It fails with the error:

*** ERROR *** config file not found
2022/04/20 19:08:51 *** ERROR *** Missing mandatory flags &{ https://snyk.io/api

Command:
./snyk-jira-sync-macos --token {} --priorityIsSeverity --jiraProjectKey AR --debug --dryrun --orgID {}

even running ./snyk-jira-sync-macos --help throws same error

**Comment by mathild3r** [comment]
Hello,

Sorry for the delay in response. 
Do you have a config file at the root of the project? Can you send it to me so I can have a look?

The config file must include all the mandatory field (but the token).

Thank you,
Mathilde

**Comment by mathild3r** [comment]
Hello @akshits96,

Do you still have an issue here?

The mandatory flags are --jiraProjectID or --jiraProjectKey, --orgID (snyk) and the --token (snyk token)

Thank you,
Mathilde

**Comment by lili2311** [comment]
Closing this issue, please re-open if you are having issues
