### ISSUE TITLE
Unable to create JIRA tickets

### ISSUE THREAD

**Issue by Ipuvi** [snyk-tech-services/jira-tickets-for-new-vulns#114]
Hi Team
I'm trying to create JIRA ticket, but facing the error mentioned in screenshot, tried using `--debug` flag to get some error info but not really able to figure the issue from same. Is there something I should be doing differently?

<img width="1440" alt="Screenshot 2022-05-18 at 7 06 59 PM" src="https://user-images.githubusercontent.com/26660033/169054656-5626fa1c-f663-48ff-8ba8-983d46d7a2e3.png">

Here is the command I've used 
`./snyk-jira-sync-macos --token=<token> --orgID=1<orgID> --projectID=<projectID> --dryRun=true --configFile=<configFileDir> --debug=true
`

**Comment by lili2311** [comment]
I am not seeing an error in the screenshot? Please can you confirm what you are seeing as the error? 
The tool is running in `dry-run` mode, is that intentional?

**Comment by Ipuvi** [comment]
Hi Lili
This one was already resolved in some other issue. This issue can be closed.
