### ISSUE TITLE
Filter out inactive projects

### ISSUE THREAD

**Issue by futurekill** [snyk-tech-services/jira-tickets-for-new-vulns#163]
Whenever I run the sync tickets get created for projects that are marked as inactive. Is there a way to tell the utility to skip those? Additionally, it'd be nice to have an include and/or exclude filter based on tag(s).

I'm running v3.35.1 if that helps.

**Comment by lili2311** [comment]
hi @futurekill we will look into this, we should indeed be filtering out inactive projects.

**Comment by lili2311** [comment]
hi @futurekill we have released a new version that will filter out inactive projects, thanks for reporting this!

**Comment by futurekill** [comment]
Awesome! thank you!

**Comment by futurekill** [comment]
@lili2311 I just rebuilt my image with the new version and now I'm getting this: 

```/snyk # /snyk/snyk-jira-sync-linux --configFile=/snyk --token=${SNYK_API_TOKEN} --debug=true
2022/10/12 15:51:47 *** INFO *** Project ID not specified - listing all projects that match the following filters:  projectCriticality:
 projectEnvironment:
 projectLifecycle:
2022/10/12 15:51:48 *** INFO *** Sending POST request to https://snyk.io/api/v1/org/REDACTED/projects
2022/10/12 15:51:48 *** INFO *** Body : {"filters":{"attributes":{"environment":[""],"lifecycle":[""]},"isMonitored":true}}
2022/10/12 15:51:48 *** INFO *** Sending POST request to https://snyk.io/api/v1/org/REDACTED/projects
2022/10/12 15:51:48 *** INFO *** retry number 0
2022/10/12 15:51:48 *** INFO *** Request on endpoint 'https://snyk.io/api/v1/org/REDACTED/projects' failed with error 422 Unprocessable Entity
2022/10/12 15:51:48 *** INFO *** Please check that all expected fields are present in the config file
2022/10/12 15:51:48 *** INFO *** Details : {"code":422,"message":"invalid value '' for attribute 'environment'","errorRef":"c04728e9-c6f1-4a9c-8d1b-07bee8d90b89"}
2022/10/12 15:51:48 *** ERROR *** Could not list the Project(s) for endpoint https://snyk.io/api/v1/org/REDACTED/projects
 Applied Filters: projectCriticality:
 projectEnvironment:
 projectLifecycle:
2022/10/12 15:51:48 *** ERROR *** Could not get read the response from endpoint https://snyk.io/api/v1/org/REDACTED/projects
2022/10/12 15:51:48 Failure, Could not get read the response from endpoint https://snyk.io/api/v1/org/REDACTED/projects```

I've removed our `orgID` from the output.

**Comment by lili2311** [comment]
Are you setting `projectEnvironment` somewhere, it looks to be set but to  / null? I've just tried with and without and get expected results. Could you share the command you are running with (redact anything sensitive)

**Comment by futurekill** [comment]
Nope, we're not setting project environment anywhere. Here's the yaml config file we're using:

```yaml
---
jira:
  jiraProjectKey: SNYK
  jiraTicketType: Task
  priorityIsSeverity: true
schema: 1
snyk:
  ifUpgradeAvailableOnly: false
  orgID: REDACTED
  priorityScoreThreshold: 10
  severity: low
  type: vuln
```

And the command I'm running (which hasn't changed):

```sh
/snyk/snyk-jira-sync-linux --configFile=/snyk --token=${SNYK_API_TOKEN}
```

The API token is being provided via an env var and it's the same one that works with older versions.

**Comment by futurekill** [comment]
I should note that most of our projects don't set projectCriticality, projectLifecycle, or projectEnvironment so I've always left them blank. The docs say they're optional so I've never set them.

**Comment by lili2311** [comment]
@futurekill thats there is a bug in the latest release it was sending empty filters to the API and the API considers this invalid, a fix is on it's way. 

This was working for me locally with and without the project filters. We are spending some time soon to improve the test coverage for scenarios like these, so this should not be possible in the future. 

Please try the new release https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/tag/4.36.1

**Comment by futurekill** [comment]
Gotcha...ok, v4.36.1 seems to be working. 

Thank you for the quick responses. :)
