### ISSUE TITLE
vulns.go contains test line of code

### ISSUE THREAD

**Issue by Tavisca-ayal-gul** [snyk-tech-services/jira-tickets-for-new-vulns#223]
While trying to use the tool I was getting an error because the api Endpoint was being reset to api.snyk.io after passing my own api endpoint in the config file.  This was only occurring at the third stage of the scan, when the tool was trying to list out the vulnerabilities of the project.

I noticed in vulns.go on line 310 a line of code was added for testing purposes. When I set the EXECUTION_ENVIRONMENT to test it works but is this intended or was this line added to test out functionality? 

![snyk_error](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/assets/89998572/836cbb60-3817-43ae-b5e9-e1c4f2fc0636)
![snyk_error2](https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/assets/89998572/f387872c-bc8c-4f85-964c-8a62292fde4c)

**Comment by aarlaud** [comment]
ACk, will push a fix asap
