### ISSUE TITLE
Optional parameter severity is not so optional

### ISSUE THREAD

**Issue by putz612** [snyk-tech-services/jira-tickets-for-new-vulns#87]
We are just spinning this up internally to create all tickets and when testing using the arguments in the example in the readme we would get an error on a projects that did not have dependencies for instance kubernetes deployment yaml.

`*** ERROR *** Could not get aggregated data from https://snyk.io/api org ####-###-###-###-### project ###-###-###-###-### issue ####`

Enabling the debug log there is a 404 on that project API endpoint

`2021/12/29 10:07:48 *** ERROR *** Request on endpoint 'https://snyk.io/api/v1/org/####-###-###-###-###/project/###-###-###-###-### /issue/####/paths' failed with error 404 Not Found`

Adding in the severity argument allowed the software to work as expected.

**Comment by mathild3r** [comment]
Hello,

I am Mathilde from tech services, just to let you know we have seen your issue and will start working on it this week.

Thank you,
Mathilde

**Comment by mathild3r** [comment]
Hello @putz612,

The latest one have debug and dryRun options. If you are not already using it, can you upgrade to that one and retry with those two options (debug and dryRun) but without the severity?

Thank you,
Mathilde

**Comment by putz612** [comment]
This was with dryrun enabled, we were testing before we deployed it.  Without the debug flag we just get the first error message, turning on the debug flag shows the 404 error.

**Comment by mathild3r** [comment]
ok,

Can you send me the full log? and the command you ran?

Thank you,
Mathilde

**Comment by putz612** [comment]
For people following along this looks to be fixed in the upcoming PR
