### ISSUE TITLE
Problem creating jiraIssue

### ISSUE THREAD

**Issue by marafu** [snyk-tech-services/jira-tickets-for-new-vulns#98]
The script sends a post request for endpoint /api/v1/org/{orgID}/project/{projectID}/issue/{issueID}/jira-issue and return a exception error entity.parse.failed with http status code 400 bad request.

I read the documentation for [create-jira-issue ](https://snyk.docs.apiary.io/#reference/projects/project-jira-issues/create-jira-issue) and it shows they are exactly the same attributes being passed in the request on line 179 of the jira.go.

I think the problem is in the request body in the description attribute.

**Request body**
`{      "fields":  {"project":    {"id":"{projectID}"}    ,"summary":"generic/project/name - Cross-Site Request Forgery (CSRF)",    "description":"\r\n \\*\\*\\*\\* Issue details: \\*\\*\\*\\*\n\r\n Title:  Cross\\-Site Request Forgery \\(CSRF\\)\n Summary:  CSRF protection is disabled by setting the value to \\_. This allows the attackers to execute requests on a user's behalf.\n Severity:  low\n PriorityScore:  434\n PriorityScoreFactors:\n  \\- Found in multiple sources\n  \\- Found in a file appearing in multiple code flows\n  \\- Has fix examples available \r\n *_Impacted file:_*\n\r   {impactedFile}\n  \\- startLine: 32\n  \\- startColumn: 9\n  \\- endLine: 32\n  \\- endColumn: 38\n\n[See this issue on Snyk|https://app.snyk.io/org/{org}/project/{projectId}]\n\n",    "issuetype":{      "name":"Bug"}      }  `

**Response body**
`{"expose":true,"statusCode":400,"status":400,"body":"{      \"fields\":  {\"project\":    {\"id\":\"number\"}    ,\"summary\":\"generic/project/name - Cross-Site Request Forgery (CSRF)\",     \"issuetype\":{      \"id\":\"number\"}      }  ","type":"entity.parse.failed"}`

Please can you help me?

**Comment by mathild3r** [comment]
I think I have managed to reproduce your bug, it has to do with the issuetype, is it possible for you to set it to "Task" instead of bug and retry? while I am investigating this?

Example: 

```
schema: 1
snyk: 
    orgID: YourOrgId
    severity:critical

jira:
    jiraTicketType: Task
    jiraProjectKey: jiraProjectId
```

**Comment by mathild3r** [comment]
Hello,

Another solution is to go on your jira project and enable bug as possible issueType, it will be automatically available in snyk afterwards.

thank you
Mathilde

**Comment by pttx00** [comment]
Yes, the problem has been solved!
